//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorFixApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErrorFixApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавь комментарий.
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлено ошибок.
        /// </summary>
        public static string AddedErrors {
            get {
                return ResourceManager.GetString("AddedErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить ошибку в БД.
        /// </summary>
        public static string AddErrorToDb {
            get {
                return ResourceManager.GetString("AddErrorToDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string CancelSave {
            get {
                return ResourceManager.GetString("CancelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать БД.
        /// </summary>
        public static string ChooseDb {
            get {
                return ResourceManager.GetString("ChooseDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string CommentLabel {
            get {
                return ResourceManager.GetString("CommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо добавить комментарий.
        /// </summary>
        public static string CommentMessage {
            get {
                return ResourceManager.GetString("CommentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение не установлено.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция удаления.
        /// </summary>
        public static string DeleteCaption {
            get {
                return ResourceManager.GetString("DeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая ошибка будет удалена. Вы уверены?.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция удаления невозможна..
        /// </summary>
        public static string DeleteNotPossible {
            get {
                return ResourceManager.GetString("DeleteNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип ошибки.
        /// </summary>
        public static string ErrorType {
            get {
                return ResourceManager.GetString("ErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт в Xlsx.
        /// </summary>
        public static string ExportToXlsx {
            get {
                return ResourceManager.GetString("ExportToXlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string IDLabel {
            get {
                return ResourceManager.GetString("IDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id должен быть больше -1.
        /// </summary>
        public static string IdMessage {
            get {
                return ResourceManager.GetString("IdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя маршрута не может содержать пробелы и другие специальные симводы (только буквы и цифры) .
        /// </summary>
        public static string IncorrectName {
            get {
                return ResourceManager.GetString("IncorrectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxID.
        /// </summary>
        public static string MaxId {
            get {
                return ResourceManager.GetString("MaxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя не задано.
        /// </summary>
        public static string NameNotSet {
            get {
                return ResourceManager.GetString("NameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступные БД отсутствуют.
        /// </summary>
        public static string NoDb {
            get {
                return ResourceManager.GetString("NoDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позиция.
        /// </summary>
        public static string PositionLabel {
            get {
                return ResourceManager.GetString("PositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позиция не задана.
        /// </summary>
        public static string PositionNotSet {
            get {
                return ResourceManager.GetString("PositionNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер маршрута.
        /// </summary>
        public static string RouteLabel {
            get {
                return ResourceManager.GetString("RouteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить в БД.
        /// </summary>
        public static string SaveToDb {
            get {
                return ResourceManager.GetString("SaveToDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задайте маршрут.
        /// </summary>
        public static string SetupRoute {
            get {
                return ResourceManager.GetString("SetupRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо задать маршрут.
        /// </summary>
        public static string SetupRouteMessage {
            get {
                return ResourceManager.GetString("SetupRouteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время не задано.
        /// </summary>
        public static string TimeStampNotSet {
            get {
                return ResourceManager.GetString("TimeStampNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего ошибок.
        /// </summary>
        public static string TotalErrors {
            get {
                return ResourceManager.GetString("TotalErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр ошибки.
        /// </summary>
        public static string ViewError {
            get {
                return ResourceManager.GetString("ViewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим работы.
        /// </summary>
        public static string WorkingType {
            get {
                return ResourceManager.GetString("WorkingType", resourceCulture);
            }
        }
    }
}
